.job:
  changes: &changes
    - .gitlab-ci.yml

stages: # List of stages for jobs, and their order of execution
  - test
  - doc
  - repository

update-readme-job:
  stage: sync
  tags:
    - datahook
  script:
    - "curl -v --request PUT --header \"PRIVATE-TOKEN:$CI_TOKEN_RCMSPB\" -F \"branch=main\" -F \"author_email=miromax\" -F \"author_name=auto_sync\" -F \"content=$(cat $CI_PROJECT_DIR/res/rcm/README.md)\" -F \"commit_message=Update README.md\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMSPB/repository/files/README.md\""
    - "curl -v --request PUT --header \"PRIVATE-TOKEN:$CI_TOKEN_RCMLNX\" -F \"branch=main\" -F \"author_email=miromax\" -F \"author_name=auto_sync\" -F \"content=$(cat $CI_PROJECT_DIR/res/rcm/README.md)\" -F \"commit_message=Update README.md\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMLNX/repository/files/README.md\""
    - "curl -v --request PUT --header \"PRIVATE-TOKEN:$CI_TOKEN_RCMROS\" -F \"branch=main\" -F \"author_email=miromax\" -F \"author_name=auto_sync\" -F \"content=$(cat $CI_PROJECT_DIR/res/rcm/README.md)\" -F \"commit_message=Update README.md\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMROS/repository/files/README.md\""
    - "curl -v --request PUT --header \"PRIVATE-TOKEN:$CI_TOKEN_RCMSVE\" -F \"branch=main\" -F \"author_email=miromax\" -F \"author_name=auto_sync\" -F \"content=$(cat $CI_PROJECT_DIR/res/rcm/README.md)\" -F \"commit_message=Update README.md\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMSVE/repository/files/README.md\""
    - "curl -v --request PUT --header \"PRIVATE-TOKEN:$CI_TOKEN_RCMNIZ\" -F \"branch=main\" -F \"author_email=miromax\" -F \"author_name=auto_sync\" -F \"content=$(cat $CI_PROJECT_DIR/res/rcm/README.md)\" -F \"commit_message=Update README.md\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMNIZ/repository/files/README.md\""
    - "curl -v --request PUT --header \"PRIVATE-TOKEN:$CI_TOKEN_RCMSTA\" -F \"branch=main\" -F \"author_email=miromax\" -F \"author_name=auto_sync\" -F \"content=$(cat $CI_PROJECT_DIR/res/rcm/README.md)\" -F \"commit_message=Update README.md\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMSTA/repository/files/README.md\""
    - "curl -v --request PUT --header \"PRIVATE-TOKEN:$CI_TOKEN_RCMNVS\" -F \"branch=main\" -F \"author_email=miromax\" -F \"author_name=auto_sync\" -F \"content=$(cat $CI_PROJECT_DIR/res/rcm/README.md)\" -F \"commit_message=Update README.md\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMNVS/repository/files/README.md\""
    - "curl -v --request PUT --header \"PRIVATE-TOKEN:$CI_TOKEN_RCMKHA\" -F \"branch=main\" -F \"author_email=miromax\" -F \"author_name=auto_sync\" -F \"content=$(cat $CI_PROJECT_DIR/res/rcm/README.md)\" -F \"commit_message=Update README.md\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMKHA/repository/files/README.md\""
    - "curl -v --request PUT --header \"PRIVATE-TOKEN:$CI_TOKEN_RCMSR\" -F \"branch=main\" -F \"author_email=miromax\" -F \"author_name=auto_sync\" -F \"content=$(cat $CI_PROJECT_DIR/res/rcm/README.md)\" -F \"commit_message=Update README.md\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMSR/repository/files/README.md\""
    - "curl -v --request PUT --header \"PRIVATE-TOKEN:$CI_TOKEN_RCMKGD\" -F \"branch=main\" -F \"author_email=miromax\" -F \"author_name=auto_sync\" -F \"content=$(cat $CI_PROJECT_DIR/res/rcm/README.md)\" -F \"commit_message=Update README.md\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMKGD/repository/files/README.md\""
  only:
    refs:
      - main
    changes:
      - res/rcm/README.md
      - .gitlab-ci.yml

build-job: # This job runs in the build stage, which runs first.
  stage: build
  # needs:
  #   - lint
  tags:
    - datahook
  script:
    - echo "Building Dockerfile..."
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "Building complete."
  only:
    refs:
      - main
    changes: *changes

deploy-job:
  stage: deploy
  tags:
    - datahook
  script:
    - docker-compose -f /opt/zaslon/go-hivehooks/docker-compose.yml up -d
  only:
    refs:
      - main
    changes: *changes
  needs:
    - build-job

update-submodules-job:
  stage: .post
  tags:
    - datahook
  script:
    - "curl --request PUT --header \"PRIVATE-TOKEN: $CI_TOKEN_RCMSPB\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMSPB/repository/submodules/source\" --data \"branch=main&commit_sha=$CI_COMMIT_SHA&commit_message=Update submodule reference\""
    - "curl --request PUT --header \"PRIVATE-TOKEN: $CI_TOKEN_RCMLNX\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMLNX/repository/submodules/source\" --data \"branch=main&commit_sha=$CI_COMMIT_SHA&commit_message=Update submodule reference\""
    - "curl --request PUT --header \"PRIVATE-TOKEN: $CI_TOKEN_RCMROS\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMROS/repository/submodules/source\" --data \"branch=main&commit_sha=$CI_COMMIT_SHA&commit_message=Update submodule reference\""
    - "curl --request PUT --header \"PRIVATE-TOKEN: $CI_TOKEN_RCMSVE\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMSVE/repository/submodules/source\" --data \"branch=main&commit_sha=$CI_COMMIT_SHA&commit_message=Update submodule reference\""
    - "curl --request PUT --header \"PRIVATE-TOKEN: $CI_TOKEN_RCMNIZ\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMNIZ/repository/submodules/source\" --data \"branch=main&commit_sha=$CI_COMMIT_SHA&commit_message=Update submodule reference\""
    - "curl --request PUT --header \"PRIVATE-TOKEN: $CI_TOKEN_RCMSTA\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMSTA/repository/submodules/source\" --data \"branch=main&commit_sha=$CI_COMMIT_SHA&commit_message=Update submodule reference\""
    - "curl --request PUT --header \"PRIVATE-TOKEN: $CI_TOKEN_RCMNVS\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMNVS/repository/submodules/source\" --data \"branch=main&commit_sha=$CI_COMMIT_SHA&commit_message=Update submodule reference\""
    - "curl --request PUT --header \"PRIVATE-TOKEN: $CI_TOKEN_RCMKHA\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMKHA/repository/submodules/source\" --data \"branch=main&commit_sha=$CI_COMMIT_SHA&commit_message=Update submodule reference\""
    - "curl --request PUT --header \"PRIVATE-TOKEN: $CI_TOKEN_RCMSR\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMSR/repository/submodules/source\" --data \"branch=main&commit_sha=$CI_COMMIT_SHA&commit_message=Update submodule reference\""
    - "curl --request PUT --header \"PRIVATE-TOKEN: $CI_TOKEN_RCMKGD\" \"http://gitlab.cloud.gcm/api/v4/projects/$CI_PROJECT_ID_RCMKGD/repository/submodules/source\" --data \"branch=main&commit_sha=$CI_COMMIT_SHA&commit_message=Update submodule reference\""
  only:
    refs:
      - main
    changes: *changes
  needs:
    - deploy-job




