
stages:
  - build 

build-package:
  stage: build
  image: python:3.7
  script:
    - pip install twine
    - python setup.py  bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/avms-${CI_COMMIT_TAG}*
    
  #only:
  #  - tags